In [ ]:
import nltk
nltk.download('punkt')

nltk.download('punkt_tab')
nltk.download('stopwords')
nltk.download('wordnet')


[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...


True

## Tokenization:

In [ ]:
text="my name is ali. i am a student of university. i want to learn programming."
from nltk.tokenize import word_tokenize
tokens=word_tokenize(text)

print(tokens)

['my', 'name', 'is', 'ali', '.', 'i', 'am', 'a', 'student', 'of', 'university', '.', 'i', 'want', 'to', 'learn', 'programming', '.']


In [ ]:
from nltk.tokenize import sent_tokenize
tokenized=sent_tokenize(text)
print(tokenized)

['my name is ali.', 'i am a student of university.', 'i want to learn programming.']


In [ ]:
from nltk.probability import FreqDist

from nltk.tokenize import word_tokenize
tokens=word_tokenize(text)
freq=FreqDist(tokens)
print(freq)

<FreqDist with 15 samples and 18 outcomes>


## Removal of stoping words:

In [ ]:
text="my name is ali. i am a student of university. i want to learn programming."

from nltk.corpus import stopwords
stop_words = set(stopwords.words('english'))
from nltk.tokenize import word_tokenize,sent_tokenize
tokenize_word=word_tokenize(text)

tokenize_word_without_stop_words=[]
for word in tokenize_word:
    if word not in stop_words:
        tokenize_word_without_stop_words.append(word)
print(tokenize_word_without_stop_words)


# print(set(tokenize_word)-set(tokenize_word_without_stop_words))




['name', 'ali', '.', 'student', 'university', '.', 'want', 'learn', 'programming', '.']


## Lemmatization:

In [ ]:
from nltk.stem import WordNetLemmatizer

lemmatizer = WordNetLemmatizer()
lemmatized_words = [lemmatizer.lemmatize(word.lower()) for word in tokenize_word_without_stop_words]
print(lemmatized_words)


['name', 'ali', '.', 'student', 'university', '.', 'want', 'learn', 'programming', '.']


## Bag of words(BOW):

In [ ]:
from sklearn.feature_extraction.text import CountVectorizer

corpus = [
    "Hello, how are you?",
    "Hi there, how is it going?",
    "Good morning!"
]

vectorizer = CountVectorizer()
X = vectorizer.fit_transform(corpus)

print(vectorizer.get_feature_names_out())
print(X.toarray())


['are' 'going' 'good' 'hello' 'hi' 'how' 'is' 'it' 'morning' 'there' 'you']
[[1 0 0 1 0 1 0 0 0 0 1]
 [0 1 0 0 1 1 1 1 0 1 0]
 [0 0 1 0 0 0 0 0 1 0 0]]


In [ ]:
corpus = [
    "i am a student and learning about chatbots and NLP",
    "chatbots are useful in many applications",
    "learning NLP is fun and interesting"
]

vectorizer = CountVectorizer()
X_bow = vectorizer.fit_transform(corpus)
print("\nVocabulary:", vectorizer.get_feature_names_out())
print("BoW Array:\n", X_bow.toarray())



Vocabulary: ['about' 'am' 'and' 'applications' 'are' 'chatbots' 'fun' 'in'
 'interesting' 'is' 'learning' 'many' 'nlp' 'student' 'useful']
BoW Array:
 [[1 1 2 0 0 1 0 0 0 0 1 0 1 1 0]
 [0 0 0 1 1 1 0 1 0 0 0 1 0 0 1]
 [0 0 1 0 0 0 1 0 1 1 1 0 1 0 0]]


In [ ]:
from sklearn.feature_extraction.text import TfidfVectorizer

tfidf = TfidfVectorizer()
X_tfidf = tfidf.fit_transform(corpus)

print(tfidf.get_feature_names_out())
print(X_tfidf.toarray())

['about' 'am' 'and' 'applications' 'are' 'chatbots' 'fun' 'in'
 'interesting' 'is' 'learning' 'many' 'nlp' 'student' 'useful']
[[0.37665395 0.37665395 0.57291007 0.         0.         0.28645504
  0.         0.         0.         0.         0.28645504 0.
  0.28645504 0.37665395 0.        ]
 [0.         0.         0.         0.42339448 0.42339448 0.32200242
  0.         0.42339448 0.         0.         0.         0.42339448
  0.         0.         0.42339448]
 [0.         0.         0.34949812 0.         0.         0.
  0.45954803 0.         0.45954803 0.45954803 0.34949812 0.
  0.34949812 0.         0.        ]]


# importing intents.json and performing nlp basic functions such as tokenization,lemmatization ,stemming and bag of words on it

In [ ]:
import json
import nltk
from nltk.stem.porter import PorterStemmer
import numpy as np


nltk.download('punkt')


stemmer = PorterStemmer()




[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Package punkt is already up-to-date!


In [ ]:

with open("intents.json", "r") as f:
    intents = json.load(f)


print("Loaded intents:")
print(json.dumps(intents, indent=2))


Loaded intents:
{
  "intents": [
    {
      "tag": "greeting",
      "patterns": [
        "Hi",
        "Hello",
        "Hey",
        "Assalamualaikum",
        "What's up?"
      ],
      "responses": [
        "Hello! How can I help you today?",
        "Hi there, what can I do for you?"
      ]
    },
    {
      "tag": "goodbye",
      "patterns": [
        "Bye",
        "See you",
        "Goodbye",
        "Khuda hafiz"
      ],
      "responses": [
        "Goodbye! Have a nice day \ud83d\ude0a",
        "Khuda hafiz! Take care."
      ]
    },
    {
      "tag": "thanks",
      "patterns": [
        "Thanks",
        "Thank you",
        "Shukriya"
      ],
      "responses": [
        "You're welcome!",
        "Happy to help!"
      ]
    }
  ]
}


In [ ]:
def tokenize(sentence):
    return nltk.word_tokenize(sentence)

def stem(word):
    return stemmer.stem(word.lower())




basically,this code tokeize the intents.json and categorize each intent from where they belong.for example,hi,hello,hey belongs to greeting intent,similarlt bye,good bye,good night belongs good bye .
after learning these patterns chatbot answer the user based on the intents in which questions of user belongs.

In [ ]:
all_words = []
tags = []
xy = []

for intent in intents['intents']:
    tag = intent['tag']
    tags.append(tag)
    for pattern in intent['patterns']:
        w = tokenize(pattern)
        all_words.extend(w)
        xy.append((w, tag))


print("Tokenized patterns:")
for pattern, tag in xy:
    print(pattern ,"->", tag)


Tokenized patterns:
['Hi'] -> greeting
['Hello'] -> greeting
['Hey'] -> greeting
['Assalamualaikum'] -> greeting
['What', "'s", 'up', '?'] -> greeting
['Bye'] -> goodbye
['See', 'you'] -> goodbye
['Goodbye'] -> goodbye
['Khuda', 'hafiz'] -> goodbye
['Thanks'] -> thanks
['Thank', 'you'] -> thanks
['Shukriya'] -> thanks


This code cleans and organizes the words and tags. It removes punctuation like( ?, !, ., ,) from the list of all words then stems each word to its root form a

after that it removes duplicates and sorts the words and tags

In [ ]:
ignore_words = ['?', '!', '.', ',']


all_words = [stem(w) for w in all_words if w not in ignore_words]
all_words = sorted(set(all_words))
tags = sorted(set(tags))

print("Cleaned Vocabulary:", all_words)
print("Tags:", tags)


Cleaned Vocabulary: ["'s", 'assalamualaikum', 'bye', 'goodby', 'hafiz', 'hello', 'hey', 'hi', 'khuda', 'see', 'shukriya', 'thank', 'up', 'what', 'you']
Tags: ['goodbye', 'greeting', 'thanks']


After tokenizing the patterns, the next step is stemming and creating a bag-of words

stemming reduces each word to its root form so that similar words are treated the same for example “running” to “run” and “morning” to “morn.” This helps the chatbot recognize different variations of the same word

 Once all words are stemmed and cleaned (removing punctuation and duplicates) we create a bag-of-words for each pattern. A bag-of-words is a numeric vector representing the presence or absence of each word in the vocabulary for that sentence For example if a sentence contains a word from the vocabulary, the corresponding position in the vector is 1 otherwise it is 0

In [ ]:
def bag_of_words(tokenized_sentence, all_words):

    tokenized_sentence = [stem(w) for w in tokenized_sentence]


    bag = np.zeros(len(all_words), dtype=np.float32)


    for idx, w in enumerate(all_words):
        if w in tokenized_sentence:
            bag[idx] = 1
    return bag




In [ ]:
X_train = []
y_train = []

print("Bag-of-Words for each pattern:")

for (pattern_sentence, tag) in xy:
    bow = bag_of_words(pattern_sentence, all_words)
    X_train.append(bow)

    label = tags.index(tag)
    y_train.append(label)

    print(f"Pattern: {pattern_sentence}")
    print(f"BoW: {bow}")
    print(f"Tag: {tag} -> Label: {label}")
    print("-------------------------")


Bag-of-Words for each pattern:
Pattern: ['Hi']
BoW: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Tag: greeting -> Label: 0
-------------------------
Pattern: ['Hello']
BoW: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Tag: greeting -> Label: 0
-------------------------
Pattern: ['Hey']
BoW: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Tag: greeting -> Label: 0
-------------------------
Pattern: ['Assalamualaikum']
BoW: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Tag: greeting -> Label: 0
-------------------------
Pattern: ['What', "'s", 'up', '?']
BoW: [0. 0. 0. 0. 0. 1. 1. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Tag: greeting -> Label: 0
-------------------------
Pattern: ['Bye']
BoW: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
Tag: goodbye -> Label: 1
-------------------------
Pattern: ['See', 'you']
BoW: [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 1. 0.]
Tag: goodbye -> Label: 1
-------------------------
Pattern: ['Goodbye']
Bo